### ISSUE TITLE
Ignores all arguments

### ISSUE THREAD

**Issue by waywardmonkeys** [greyblake/cargo-testify#2]
When running `cargo testify --features whatever`, nothing actually uses that argument (since `cargo-testify` doesn't pay attention to the arguments...)

**Comment by greyblake** [comment]
Thanks for the feature request.
I'll try to address it this Wed at Rust hackathon.

**Comment by greyblake** [comment]
@waywardmonkeys This is addressed in `v0.2.0`, that was just released. Please give it a try.
