### ISSUE TITLE
Add ignore pattern

### ISSUE THREAD

**Issue by Hugal31** [greyblake/cargo-testify#7]
I often work with emacs, and this app reacts to the creation of temporary files like `.#lib.rs`, or `lib.rs~`.

It would be nice to only look for modification of not-hidden `*.rs` files inside `src` and `tests` directories, or make it configurable, maybe with regex or glob patterns.

**Comment by greyblake** [comment]
Hey! Thanks for the report. Would you like to specify the regexp as options in command line?
I think, probably we should come up with good default list of ignore regexps + add ability to customize it if necessary. What do you think?

**Comment by Hugal31** [comment]
Actually, I have started to implement it with glob patterns. Check [my fork](https://github.com/Hugal31/cargo-testify/tree/feature/glob-matching) if you want.

I plan to add also an ignore pattern list, and of course the possibility to configure from the command line.

**Comment by Hugal31** [comment]
And what about `.gitignore` support with the [ignore crate](https://docs.rs/ignore/0.4.2/ignore/)? :slightly_smiling_face:

**Comment by greyblake** [comment]
Thanks. You fixed it https://github.com/greyblake/cargo-testify/pull/8

And it's released in `v0.3.0`. 

I apologize for the delay.
